apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ci4zrw037-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ci4zrw037-nodejs 
  name: ci4zrw037-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ci4zrw037-nodejs 
